server:
  port: ${PORT:5000}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dojo-back}?useUnicode=yes&characterEncoding=UTF-8
    username: ${DB_USER:dojo-back}
    password: ${DB_PASS:dojo-back}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: tech.gregori.kotlindojoback.config.MariaDBCustomDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: tech.gregori.kotlindojoback.config.MariaDBCustomDialect
      format_sql: true
    database-platform: tech.gregori.kotlindojoback.config.MariaDBCustomDialect
#  sql:
#    init:
#      mode: always

app:
  jwt-security:
    jwt-secret: $uperCalifragilisticExpialidoci0usN3v3rF41lT0D3c3iV3U$
    expiration-time: 86400000
